import type { SectionContent, SubPageContent } from "./types";
import { img } from "./types";

const base = "/corporate-groups";

const sub = (
  slug: string,
  seoTitle: string,
  seoDescription: string,
  headline: string,
  tagline: string,
  poster: string,
  posterAlt: string,
  overview: string[],
  experiences: string[],
  atAGlance: { label: string; value: string }[],
): SubPageContent => ({
  slug, basePath: base, theme: "corporate", seoTitle, seoDescription,
  eyebrow: "Corporate & Groups", headline, tagline,
  posterSrc: poster, posterAlt, overview, experiences, atAGlance,
});

export const corporateContent: SectionContent = {
  theme: "corporate",
  basePath: base,
  hubTitle: "Corporate & Group Plans",
  seoTitle: "Corporate Team Outings Odisha | Group Retreats & Offsites",
  seoDescription:
    "Premium corporate team outings & retreats in Odisha — nature team-building, leadership offsites, annual events & incentive tours. GST invoicing. Min 15 people.",
  eyebrow: "Team Outings",
  headline: "Where Teams Breathe, Bonds Are Built",
  subhead:
    "Nature-immersive corporate experiences in Odisha — your team returns with shared stories no worksheet could create.",
  intro: [
    "Fewer crowds, more space — your team gets the entire experience, not a shared resort. Costs run 30–40% lower than Goa, Coorg, or Manali for comparable experiences.",
    "Unique activities — tribal village visits, mangrove safaris, summit treks, and art sessions — with excellent connectivity via Biju Patnaik International Airport and full GST-compliant invoicing for every booking.",
  ],
  portals: [
    { tier: 2, label: "Team-Building in the Wild", tagline: "Real challenges, real teams", href: `${base}/team-building`, theme: "corporate", posterSrc: img("photo-1531545514256-b1400bc00f31"), posterAlt: "Team collaborating outdoors" },
    { tier: 2, label: "Leadership Offsite", tagline: "Space to think, time to align", href: `${base}/leadership-offsite`, theme: "corporate", posterSrc: img("photo-1517048676732-d65bc937f952"), posterAlt: "Leadership team in discussion" },
    { tier: 2, label: "Annual Day & Events", tagline: "Celebrate your team's year", href: `${base}/annual-day`, theme: "corporate", posterSrc: img("photo-1511795409834-ef04bbd61622"), posterAlt: "Large company celebration event" },
    { tier: 2, label: "Sales Incentive Trips", tagline: "Reward the extraordinary", href: `${base}/incentive-trips`, theme: "corporate", posterSrc: img("photo-1469474968028-56623f02e42e"), posterAlt: "Premium scenic reward destination" },
    { tier: 2, label: "Day Out Packages", tagline: "One-day group escapes", href: `${base}/day-out`, theme: "corporate", posterSrc: img("photo-1502920917128-1aa500764cbd"), posterAlt: "Group day trip outdoors" },
    { tier: 2, label: "Custom Enterprise", tagline: "Fully bespoke planning", href: `${base}/custom`, theme: "corporate", posterSrc: img("photo-1497366754035-f200968a6e72"), posterAlt: "Corporate meeting space" },
  ],
  packages: [
    { title: "Day Out Plan", duration: "1 day · 15–80 people", fromPrice: 3499, highlights: ["Activities + lunch", "Cultural demo", "Transport · GST invoice"], href: `${base}/day-out` },
    { title: "Annual Company Trip", duration: "2N/3D · 50–200 people", fromPrice: 8999, highlights: ["Cultural performance + feast", "Adventure activities", "Custom branding"], href: `${base}/annual-day` },
    { title: "Weekend Retreat", duration: "2N/3D · 20–60 people", fromPrice: 9999, highlights: ["Team-building programme", "Eco-stay", "Bonfire debrief"], href: `${base}/team-building` },
  ],
  comparison: {
    headers: ["Plan", "People", "Duration", "GST", "From"],
    rows: [
      ["Day Out Plan", "15–80", "1 day", "✅", "₹3,499"],
      ["Weekend Retreat", "20–60", "2N/3D", "✅", "₹9,999"],
      ["Leadership Offsite", "8–20", "3N/4D", "✅", "On Request"],
      ["Annual Company Trip", "50–200", "2N/3D", "✅", "₹8,999"],
      ["Sales Incentive Tour", "5–15", "4N/5D", "✅", "On Request"],
      ["Custom Enterprise", "Any", "Any", "✅", "Bespoke"],
    ],
  },
  inclusions: [
    "Private AC coach + airport/rail transfers",
    "Full private group accommodation",
    "All meals with Odia & standard options",
    "Professional facilitators & guides",
    "GST-compliant tax invoice",
    "24/7 trip captain helpline",
  ],
  faqs: [
    { question: "Do you provide GST invoices for corporate bookings?", answer: "Yes — every corporate booking includes a full GST-compliant tax invoice." },
    { question: "What is the minimum group size for corporate packages?", answer: "Most corporate plans start at 15 people; day-out plans at 15–20, annual trips up to 200." },
    { question: "Can you arrange conference rooms or AV equipment?", answer: "Yes, venues with conference and AV facilities can be arranged on request." },
    { question: "What team-building activities are available?", answer: "Raft-building, forest navigation, jungle cooking, trust trails, and facilitated bonfire debriefs." },
    { question: "Do you offer customisation for specific company cultures?", answer: "Absolutely — our custom enterprise plans are designed entirely around your brief and culture." },
    { question: "Is travel insurance included?", answer: "Travel insurance can be added on request; safety equipment and first aid are always included." },
  ],
  subpages: [
    sub("team-building", "Corporate Team Building Odisha | Forest Challenges",
      "Nature-based corporate team-building in Odisha's forests & rivers — raft-building, navigation challenges, jungle cooking & bonfire debriefs. GST invoices available.",
      "Real Challenges. Real Teams. Real Nature.", "20–100 people · 2–4 nights · forest, river, and tribal settings.",
      img("photo-1531545514256-b1400bc00f31"), "Team building activity in a forest setting",
      ["Teams face real challenges in Odisha's forests, rivers, and tribal landscapes — not trust-fall clichés, but genuine collaboration under open sky.",
       "Choose half-day, full-day, overnight, or a 2-night facilitated programme, each closing with a bonfire debrief led by an optional executive coach."],
      ["Raft-building challenge on the Mahanadi / Budhabalanga", "Forest navigation with map and compass — no phones", "Jungle cooking challenge over open fire", "Sabotage & problem-solving games", "Trust blindfold forest trail", "Bonfire debrief & alignment session"],
      [{ label: "Group", value: "20–100 people" }, { label: "Duration", value: "Half-day to 2 nights" }, { label: "Locations", value: "Similipal, Satkosia, Koraput, Chilika" }]),
    sub("leadership-offsite", "Leadership Offsite Odisha | Private Executive Retreats",
      "Exclusive 3–5 night leadership offsites in Odisha's private eco-lodges & heritage properties. Facilitated sessions, curated experiences & fine dining. 8–20 people.",
      "Space to Think. Time to Align. Nature to Reset.", "For senior leadership teams who need more than a meeting room with a view.",
      img("photo-1517048676732-d65bc937f952"), "Executive leadership team in a retreat setting",
      ["Mornings hold facilitated strategic alignment sessions; afternoons unfold into curated outdoor experiences; evenings are fine dining and open-ended conversation in a natural setting.",
       "Venues range from private heritage estates in Koraput to full beachfront resort buyouts in Puri."],
      ["Facilitated strategic alignment (BYO or recommended facilitator)", "Sunrise at Konark with private pre-dawn access", "Dawn boat meditation on Chilika", "Private Odissi performance at camp", "Contemplative temple-circuit walk", "Stargazing with a naturalist at Similipal"],
      [{ label: "Group", value: "8–20 people" }, { label: "Duration", value: "3–5 nights" }, { label: "Venues", value: "Heritage estates & private resorts" }]),
    sub("annual-day", "Corporate Annual Day Odisha | Company Events & Milestones",
      "Plan your company's annual day or milestone in Odisha — cultural performances, Odia feast, adventure activities & customised experiences for 50–200 people.",
      "Celebrate Your Team's Year the Right Way", "50–200 people · 1–2 nights · cultural performances + adventure + grand feast.",
      img("photo-1511795409834-ef04bbd61622"), "Large corporate annual day celebration",
      ["From a traditional Odia welcome of diyas and music to an evening of Gotipua, Odissi, or tribal folk performance, your annual day becomes an event the team talks about all year.",
       "A 12-dish Mahaprasad-style feast, open-air games, custom branding, and optional fireworks complete the celebration."],
      ["Traditional Odia arrival welcome", "Full-day sightseeing or adventure", "Evening cultural performance", "Grand 12-dish Odia feast", "Open-air games & team activities", "Custom branding, photo booths & gifting"],
      [{ label: "Group", value: "50–200 people" }, { label: "Duration", value: "1–2 nights" }, { label: "Highlight", value: "Cultural performance + feast" }]),
    sub("incentive-trips", "Sales Incentive Tour Odisha | Premium Reward Trips",
      "Reward top performers with exclusive 3–5 night private Odisha experiences — Konark private sunrise, Chilika houseboat, helicopter charters & heritage fine dining.",
      "Reward the Extraordinary with the Extraordinary", "5–15 people · 3–5 nights · premium private access · GST invoice.",
      img("photo-1469474968028-56623f02e42e"), "Premium scenic reward trip destination",
      ["Reward your highest achievers with experiences money rarely buys — private pre-dawn temple access, a houseboat night on Chilika, and dinners in heritage settings.",
       "Each trip closes with a personalised Tarakasi silver memento engraved with the winner's name."],
      ["Private pre-dawn Konark temple access", "Chilika houseboat night with chef & crew", "Helicopter survey of Satkosia gorge (charter)", "Private dinner at Rajarani Temple grounds", "Engraved Tarakasi silver memento", "VIP darshan at Jagannath Puri"],
      [{ label: "Group", value: "5–15 people" }, { label: "Duration", value: "3–5 nights" }, { label: "Access", value: "Premium & private" }]),
    sub("day-out", "Corporate Day Out Near Bhubaneswar | Group Day Trips",
      "One-day corporate outing packages near Bhubaneswar for groups of 15–80 — activities, lunch, cultural demo & transport included. GST invoicing available.",
      "A Full Day Out, Fully Handled", "15–80 people · 1 day · activities + lunch + cultural demo + transport.",
      img("photo-1539635278303-d4002c07eae3"), "Corporate group enjoying an outdoor day trip activity",
      ["Perfect for a quick team reset — choose from Dhauli & Nandankanan, a Chilika day cruise, Konark & Chandrabhaga, or a Satkosia river safari, all within 30 minutes to 2 hours of Bhubaneswar.",
       "Every option includes activities, lunch, a cultural demo, transport, and a GST invoice."],
      ["Dhauli Peace Pagoda & Nandankanan zoo safari", "Chilika day cruise with dolphin spotting", "Konark & Chandrabhaga temple + beach", "Satkosia river safari & nature walk", "Riverside or resort lunch", "Round transport from Bhubaneswar"],
      [{ label: "Group", value: "15–80 people" }, { label: "Duration", value: "1 day" }, { label: "From", value: "₹3,499/person" }]),
    sub("custom", "Custom Corporate Tours Odisha | Bespoke Enterprise Travel",
      "Fully bespoke corporate travel for large enterprises — designed to your brief, culture & budget. Any group size, any duration, any experience type. 24-hour proposal.",
      "Built Entirely Around Your Brief", "Any group size · any duration · any experience type.",
      img("photo-1497366754035-f200968a6e72"), "Corporate planning and meeting space",
      ["Tell us your company, group size, dates, budget, and the experience you're imagining — team-building, offsite, annual day, incentive, or something entirely new.",
       "Within 24 hours you'll receive a detailed day-wise itinerary, venue options, an itemised cost breakdown, and a GST invoice template."],
      ["Discovery call to understand your culture & goals", "Day-wise itinerary in 24 hours", "Venue options across Odisha", "Itemised, transparent cost breakdown", "GST invoice template provided", "Dedicated planner end-to-end"],
      [{ label: "Group", value: "Any size" }, { label: "Duration", value: "Flexible" }, { label: "Response", value: "Proposal in 24 hours" }]),
  ],
};
