import type { SectionContent, SubPageContent } from "./types";
import { img } from "./types";

// Hub lives at /spiritual-journeys, subpages live at /spiritual/[slug].
const hubBase = "/spiritual-journeys";
const subBase = "/spiritual";

const sub = (
  slug: string, seoTitle: string, seoDescription: string, headline: string,
  tagline: string, poster: string, posterAlt: string, overview: string[],
  experiences: string[], atAGlance: { label: string; value: string }[],
): SubPageContent => ({
  slug, basePath: subBase, theme: "spiritual", seoTitle, seoDescription,
  eyebrow: "Sacred India", headline, tagline, posterSrc: poster, posterAlt,
  overview, experiences, atAGlance,
});

export const spiritualContent: SectionContent = {
  theme: "spiritual",
  basePath: hubBase,
  hubTitle: "Spiritual Journeys",
  seoTitle: "Hindu Pilgrimage Tours | Char Dham, Jyotirlinga & Kashi",
  seoDescription:
    "Sacred journeys across India — Char Dham Yatra, 12 Jyotirlinga circuit, Shakti Peetha trail & Varanasi tirtha. Guided, family-friendly pilgrimage packages.",
  eyebrow: "Sacred India",
  headline: "Journeys of Devotion, Routes of the Sacred",
  subhead:
    "From the ghats of Kashi to the peaks of Char Dham — tirtha, Jyotirlinga, and Shakti Peetha journeys, planned with care and reverence.",
  intro: [
    "Tirtha means a sacred crossing point — a place where the physical and spiritual meet. In India, tirtha travel spans holy cities, river ghats, Jyotirlingas, Char Dham circuits, and powerful goddess shrines.",
    "These journeys are not only temple darshan. They are rhythm, route, ritual, and reflection — moving through holy cities, riverbanks, mountain shrines, and timeless places of worship across India.",
  ],
  portals: [
    { tier: 2, label: "Kashi & Varanasi", tagline: "Ghats & Ganga Aarti", href: `${subBase}/kashi-varanasi`, theme: "spiritual", posterSrc: "/spiritual-varanasi-ghat.png", posterAlt: "Varanasi ghats with boats and temples along the Ganga" },
    { tier: 2, label: "Char Dham Yatra", tagline: "Four sacred dhams", href: `${subBase}/char-dham`, theme: "spiritual", posterSrc: img("photo-1626621341517-bbf3d9990a23"), posterAlt: "Kedarnath temple surrounded by snow-capped Himalayan peaks" },
    { tier: 2, label: "Jyotirlinga Circuit", tagline: "12 Shiva shrines", href: `${subBase}/jyotirlinga`, theme: "spiritual", posterSrc: img("photo-1609766857041-ed402ea8069a"), posterAlt: "Ancient Shiva temple with ornate stone carvings" },
    { tier: 2, label: "Shakti Peetha Trail", tagline: "The goddess circuit", href: `${subBase}/shakti-peetha`, theme: "spiritual", posterSrc: img("photo-1604608672516-f1b9b1d37076"), posterAlt: "Hindu goddess temple decorated with flowers and red cloth" },
    { tier: 2, label: "Sacred River Journeys", tagline: "Ghats & rituals", href: `${subBase}/sacred-rivers`, theme: "spiritual", posterSrc: "/spiritual-boat.png", posterAlt: "Boat on the sacred river with temple ghats" },
    { tier: 2, label: "South India Tirtha", tagline: "Southern sacred routes", href: `${subBase}/south-india-tirtha`, theme: "spiritual", posterSrc: img("photo-1582510003544-4d00b7f74220"), posterAlt: "Ornate South Indian temple gopuram tower" },
    { tier: 2, label: "Custom Pilgrimage", tagline: "Your own sacred route", href: `${subBase}/custom-pilgrimage`, theme: "spiritual", posterSrc: "/spiritual-varanasi-bg.png", posterAlt: "Varanasi skyline with temples at golden hour" },
  ],
  packages: [
    { title: "Kashi Darshan", duration: "2N/3D · Varanasi, ghats, Ganga Aarti", highlights: ["First-time pilgrims", "Kashi Vishwanath darshan", "Boat ride on the Ganga"], href: `${subBase}/kashi-varanasi` },
    { title: "Char Dham Yatra", duration: "9N/10D · Yamunotri to Badrinath", highlights: ["Serious devotees", "Helicopter & road options", "Senior-friendly planning"], href: `${subBase}/char-dham` },
    { title: "Jyotirlinga Trail", duration: "7N–15N · Shiva shrine circuit", highlights: ["Shiva followers", "Multiple route options", "Story & ritual at each shrine"], href: `${subBase}/jyotirlinga` },
  ],
  comparison: {
    headers: ["Package", "Duration", "Focus", "Ideal For"],
    rows: [
      ["Kashi Darshan", "2N/3D", "Varanasi, ghats, Ganga Aarti", "First-time pilgrims"],
      ["Char Dham Yatra", "9N/10D", "Yamunotri, Gangotri, Kedarnath, Badrinath", "Serious devotees"],
      ["Jyotirlinga Trail", "7N–15N", "Shiva shrine circuit", "Shiva followers"],
      ["Shakti Peetha Yatra", "5N–12N", "Goddess circuit", "Family & Navratri travel"],
      ["Custom Tirtha Tour", "Flexible", "Mixed sacred route", "Private groups & elders"],
    ],
  },
  faqs: [
    { question: "What is the best season for Char Dham Yatra?", answer: "The Char Dham shrines open around late April/May and close by October/November. May–June and September are popular." },
    { question: "Are your pilgrimages senior and family friendly?", answer: "Yes — we offer senior-friendly itineraries with helicopter options for Char Dham and managed darshan queues." },
    { question: "Can circuits be combined?", answer: "Yes. Char Dham, Jyotirlinga, Shakti Peetha, and Varanasi routes are designed to link together." },
    { question: "Do you help with darshan and queue planning?", answer: "We arrange darshan timing and, where available, special access to reduce waiting." },
    { question: "Do you cover South India temples?", answer: "Yes — Rameshwaram, Tirupati, Srirangam, Madurai and more are part of our South India tirtha routes." },
  ],
  subpages: [
    sub("kashi-varanasi", "Varanasi Spiritual Tour | Kashi Vishwanath & Ganga Aarti",
      "Kashi Vishwanath darshan, Dashashwamedh Ghat Ganga Aarti, Assi Ghat sunrise & Ganga boat rides. Guided Varanasi spiritual tour packages.",
      "Kashi — The Eternal City of Light", "Temple devotion, river worship, ghats, and the daily ritual life of the world's oldest living city.",
      "/spiritual-varanasi-ghat.png", "Varanasi ghats with boats and temples along the sacred Ganga river",
      ["Varanasi combines temple devotion, river worship, ghats, and daily ritual life like nowhere else. It is the ideal lead destination for any spiritual journey.",
       "Witness Kashi Vishwanath darshan, the grand Dashashwamedh Ghat Ganga Aarti, quiet sunrise at Assi Ghat, and the slow rhythm of boat rides on the Ganga."],
      ["Kashi Vishwanath darshan", "Dashashwamedh Ghat Ganga Aarti", "Assi Ghat sunrise & evening experiences", "Boat rides on the Ganga", "Ghat walks & sacred-city storytelling", "Incense, lamps & temple bells"],
      [{ label: "Duration", value: "2N / 3D (Kashi Darshan)" }, { label: "Ideal For", value: "First-time pilgrims" }, { label: "Mood", value: "Devotional, riverine" }]),
    sub("char-dham", "Char Dham Yatra 2026 | Kedarnath & Badrinath Package",
      "Char Dham Yatra packages — Yamunotri, Gangotri, Kedarnath & Badrinath. Route map, opening season, helicopter & road options, senior-friendly planning.",
      "The Char Dham Yatra", "Yamunotri, Gangotri, Kedarnath, Badrinath — one of the most revered pilgrimage routes in India.",
      img("photo-1626621341517-bbf3d9990a23"), "Kedarnath temple with snow-capped Himalayan mountains in background",
      ["The Char Dham circuit of Uttarakhand — Yamunotri, Gangotri, Kedarnath, and Badrinath — is traditionally completed clockwise and remains the strongest pilgrimage route for serious devotees.",
       "Yamunotri is the origin of the Yamuna; Gangotri of the Ganga; Kedarnath a Shiva Jyotirlinga; and Badrinath a major Vaishnava dham. We plan route, season, altitude, and travel mode around your group."],
      ["Darshan at all four dhams in traditional order", "Route map & opening-season guidance", "Helicopter and road options", "Fitness and altitude guidance", "Senior-friendly & family planning", "Managed stay and travel logistics"],
      [{ label: "Duration", value: "9N / 10D" }, { label: "Ideal For", value: "Serious devotees" }, { label: "Options", value: "Helicopter or road" }]),
    sub("jyotirlinga", "12 Jyotirlinga Tour Package | Shiva Shrine Pilgrimage",
      "Pilgrimage circuit of the 12 Jyotirlingas — Somnath, Mahakaleshwar, Kashi Vishwanath, Rameshwaram & more. Story, route, and ritual at each sacred Shiva shrine.",
      "The Twelve Jyotirlingas", "The most sacred Shiva shrines in India, on a circuit built for devotion.",
      img("photo-1604608672516-f1b9b1d37076"), "Ancient Shiva temple shrine",
      ["The 12 Jyotirlingas are among the most sacred Shiva shrines in India — Somnath, Mallikarjuna, Mahakaleshwar, Omkareshwar, Kedarnath, Bhimashankar, Kashi Vishwanath, Trimbakeshwar, Vaidyanath, Nageshwar, Rameshwaram, and Grishneshwar.",
       "Each subpage covers the temple story, mythological significance, best season, route and access, and nearby sacred sites — across flexible 7 to 15 night circuits."],
      ["Darshan across the 12 Jyotirlinga shrines", "Temple story & mythology at each site", "Best-season & route guidance", "Multiple circuit options", "Nearby sacred-site additions", "Spiritual experience highlights"],
      [{ label: "Duration", value: "7N–15N" }, { label: "Ideal For", value: "Shiva followers" }, { label: "Scope", value: "All-India circuit" }]),
    sub("shakti-peetha", "Shakti Peetha Yatra | Goddess Pilgrimage Circuit",
      "Shakti Peetha pilgrimage — Kamakhya, Vaishno Devi, Kalighat, Tarapith, Biraja & more. Goddess-focused devotional circuit, ideal for Navratri & family travel.",
      "The Shakti Peetha Trail", "A powerful goddess circuit and sister journey to the Jyotirlingas.",
      img("photo-1582510003544-4d00b7f74220"), "Goddess temple decorated in red and gold",
      ["The Shakti Peetha journey gives the spiritual circuit a strong goddess dimension and a powerful all-India theme. It pairs beautifully with Jyotirlinga travel.",
       "Visit Kamakhya, Vaishno Devi, Kalighat, Tarapith, Biraja, and other major Shakti Peethas — especially meaningful for Navratri planning and women-led pilgrimages."],
      ["Darshan at major Shakti Peethas", "Kamakhya, Vaishno Devi, Kalighat & more", "Navratri-aligned planning", "Family & women-led pilgrimage focus", "Combine with Jyotirlinga routes", "Devotional storytelling at each shrine"],
      [{ label: "Duration", value: "5N–12N" }, { label: "Ideal For", value: "Family & Navratri travel" }, { label: "Pairs With", value: "Jyotirlinga circuit" }]),
    sub("sacred-rivers", "Sacred River Journeys India | Ganga Aarti & Ghat Rituals",
      "Sacred river journeys across India — Ganga Aarti, holy bathing, boat rides & sunrise rituals. Meditative ghat experiences with flowing-water serenity.",
      "Sacred River Journeys", "India's river ghats are as sacred as its temples — water, ritual, and morning-to-evening devotional rhythm.",
      "/spiritual-boat.png", "Boat on the sacred river with temple ghats in the background",
      ["India's river ghats carry the same sanctity as its temples, connecting the spiritual journey with water, ritual, and the rhythm from sunrise to sunset.",
       "Experience Ganga Aarti, guided holy bathing, gentle boat rides, sunrise and sunset rituals, and meditation by sacred rivers."],
      ["Ganga Aarti ceremonies", "Holy bathing guidance", "Sunrise & sunset river rituals", "Gentle boat rides", "Meditation near sacred rivers", "Soft reflections, lamps & diyas"],
      [{ label: "Mood", value: "Calm, meditative" }, { label: "Focus", value: "River ritual & reflection" }, { label: "Pairs With", value: "Kashi & Varanasi" }]),
    sub("south-india-tirtha", "South India Temple Tour | Rameshwaram & Tirupati",
      "South India tirtha tours — Rameshwaram, Tirupati, Srirangam & Madurai. Temple darshan, sacred bathing & senior-friendly pilgrimage itineraries.",
      "South India Tirtha", "The major southern sacred routes, gathered into one devotional journey.",
      img("photo-1621331169367-1a2c0c8c1a8e"), "South Indian temple gopuram",
      ["This route brings together the southern sacred centres many pilgrims want in one place — Rameshwaram, Tirupati, Srirangam, Madurai, and more.",
       "We plan temple darshan and queues, sacred bathing rituals, coastal shrine journeys, and senior-friendly itineraries with a structured, practical, route-based flow."],
      ["Temple darshan & queue planning", "Sacred bathing rituals", "Coastal shrine journeys", "Family pilgrimage packages", "Senior-citizen-friendly itineraries", "Structured, route-based travel"],
      [{ label: "Tone", value: "Devotional & practical" }, { label: "Focus", value: "Southern sacred centres" }, { label: "Ideal For", value: "Families & elders" }]),
    sub("custom-pilgrimage", "Custom Pilgrimage Tour India | Bespoke Tirtha Route",
      "Build a custom Hindu pilgrimage across India — mixed sacred routes for private groups and elders. Flexible duration, family-focused, planned with reverence.",
      "Your Own Sacred Route", "A bespoke mixed tirtha journey, shaped entirely around your devotion and your group.",
      "/spiritual-varanasi-bg.png", "Varanasi skyline with temples at golden hour",
      ["Some journeys don't fit a fixed circuit. Tell us the shrines, rivers, and cities that matter to your family, and we'll weave them into a single, reverent route.",
       "Flexible in duration and focused on the comfort of elders and families, your custom pilgrimage is planned so you feel guided, never sold to."],
      ["Mixed sacred route across India", "Shrines, rivers & cities of your choice", "Flexible duration", "Comfort-first for elders & families", "Managed darshan & logistics", "A guided, unhurried experience"],
      [{ label: "Duration", value: "Flexible" }, { label: "Ideal For", value: "Private groups & elders" }, { label: "Approach", value: "Guided, reverent" }]),
  ],
};
